### PR TITLE
Convert project structure into Maven structure

### PR DESCRIPTION
**Pull request by flyhard**
I'd like to be able to include this library into my code without adding it's source directly, so I think moving towards a maven structure and maybe even publishing it to maven central is a usefull thing.

### CODE REVIEW

**Comment by adamheinrich** [comment]
Hi, thank you for the request, Maven support is a good idea.

Commit 6d973ca5cda3a3feb759ae579501f38a0685d6f0 includes a .gitignore file, is it necessary for Maven? I think it contains some redundant thing.

**Comment by flyhard** [comment]
Yes, I normally put in the ignore list for my IDEs so that the IDE files don't get checked in.

**Comment by sid9102** [comment]
@adamheinrich Could you publish to Maven central? It would be nice to be able to use Gradle instead of downloading and building a jar.

**Comment by adamheinrich** [comment]
@sid9102 Yes, I only need some time to read and understand the instructions :-)

**Pull request merged**
